# Generated by Django 2.0.7 on 2018-08-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data_normalization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketnormalizeddata',
            name='from_currency',
            field=models.CharField(choices=[('BTC', 'BITCOIN'), ('ETH', 'ETHEREUM'), ('XRP', 'RIPPLE'), ('LTC', 'LITECOIN')], max_length=255),
        ),
        migrations.AlterField(
            model_name='marketnormalizeddata',
            name='to_currency',
            field=models.CharField(choices=[('BTC', 'BITCOIN'), ('ETH', 'ETHEREUM'), ('XRP', 'RIPPLE'), ('LTC', 'LITECOIN')], max_length=255),
        ),
    ]
